# Generated by Django 5.2.5 on 2025-11-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem destaque do produto', upload_to='produtos_imgs/'),
        ),
    ]
